### ISSUE TITLE
How to install this?

### ISSUE THREAD

**Issue by SpencerDub** [MikhaD/wordle#33]
Sorry for such a rudimentary question!

I run a small personal server using YunoHost, and I'd love to install Wordle+ for myself and my family, but I can't quite seem to figure out how to do it. I tried just cloning the git repo into the the website directory, but when I did, navigating to the `index.html` file didn't load the game.

I'm certainly overlooking something, but any help would be appreciated. Perhaps that could also be spun up into some documentation?

Thanks in advance.

**Comment by JakeWasChosen** [comment]
You need to run "npm run build"

**Comment by MikhaD** [comment]
Jake is correct. This repository only contains the source files. I have an action that runs when I make changes that compiles the Svelte on a separate branch which is used by GitHub pages to host the website.
In order to run the game locally you need to:
1) clone the repo
2) make sure you have Node v16+ installed
3) run `npm i` in the root directory
4) run `npm run build`
Once that's done you only need the public directory. Let me know if you run into anymore issues, good luck.
