### ISSUE TITLE
Offload analytics into a web worker

### ISSUE THREAD

**Issue by MikhaD** [MikhaD/wordle#41]
**Description**
Try using partytown to offload the Google analytics code into a web worker to see if there is any increase in performance. 

**Reasoning**
The animations lag on mobile, leading me to believe there is performance to be gained.

**Comment by MikhaD** [comment]
Turns out my animations were lagging in Firefox mobile even if analytics were removed. The lag is only on Firefox. Installing the PWA from Chrome eliminated the lag.
Taking this into consideration I think partytown is overkill.

**Comment by lukeswitz** [comment]
Why are you using Google analytics in an open source project in the first place?

**Comment by MikhaD** [comment]
Because I want to see how many people are using the thing I created. As per our previous conversation I have added an if statement to prevent analytics running if the domain is different, so that even identical clones of the repo will not run the analytics script.

**Comment by lukeswitz** [comment]
While I understand that it may not be illegal to include this service, I am personally uncomfortable with my data being tracked and collected by a third-party service without my explicit consent.

As a user, I believe that my privacy should be protected and that I should have the ability to opt-out of data collection if I so choose. I also believe that any data collection should be done with my informed consent, and that any data collected should be protected and not shared with any third parties without my permission.

I understand that you may have included Google Analytics in order to gain insights and improve the project, but I would kindly ask that you consider the privacy implications for your users and offer them the option to opt-out of data collection. I would also appreciate it if you could provide more transparency about how the data is being used, and how it's protected.

Thank you for your consideration.

Sincerely,

Luke Switzer
