### ISSUE TITLE
Option to disable background symbols

### ISSUE THREAD

**Issue by goombapatrol** [MikhaD/wordle#51]
**Description**
I'd like to request a menu toggle to hide the large 'Hourly' and 'Infinite' symbols that appear in background behind squares when playing said modes.

**Reasoning**
It's really distracting and harder to focus on the field and tiles when it's overlaid as such. Could have a small icon at the top, or not at all (it doesn't seem necessary). Just not on the squares.

Nice work, thanks for making this.

![Wordle+__An_infinite_word_guessing_game_-_Google__2022-07-21_08-21-58](https://user-images.githubusercontent.com/7359713/180223983-10b19be3-b721-4558-ba15-e2224add5c50.png)

**Comment by goombapatrol** [comment]
Setting **--bg-secondary** in CSS to **#FFFFFF** can do the trick in meantime, for anybody else who wants to hide it. (for Light theme)

**Comment by MikhaD** [comment]
Without the symbols there is no immediate indication of the game mode being played. I wasn't aware anyone played in light mode. I'd say try dark mode in the mean time, I'll consider adding a toggle for the symbols.

**Comment by MikhaD** [comment]
I have decided against adding a toggle for the background symbols, as they are the only way to immediately identify which game mode one is currently playing, and I do not wish to add additional settings unless absolutely necessary, as the settings already need to be scrolled on small devices, and I want the tips at the bottom to be immediately visible.

However, I do agree that the symbols are a bit distracting in light mode, so I have added a new CSS variable called `--mode-symbol-color`. It is set to `var(--bg-secondary)` in dark mode, keeping it the same, but `#f1f1f1` in light mode instead of `#e0e0e0`. Hopefully this reduction in contrast reduces distraction.
### Before:
![before](https://user-images.githubusercontent.com/31388146/212472739-7f417ac4-95b1-45b8-b0cf-571d2a3dd418.png)
### After:
![after](https://user-images.githubusercontent.com/31388146/212472749-e0ec648a-cb20-4b7f-8ce9-9db307b2b94d.png)
