### ISSUE TITLE
Multilanguage support

### ISSUE THREAD

**Issue by Zibri** [MikhaD/wordle#59]
Hello!
I was starting to do a webapp of the original wordle, then I saw this repository....
I was also planning to add more languages.
If you put application strings and wordlists in separate files it would be easy for the comminity to translate it in all possible languages.
If anyone is interested here is the android APK of the last version appeared on the original author website:
[Wordle.zip](https://github.com/MikhaD/wordle/files/10016116/Wordle.zip)

**Comment by MikhaD** [comment]
By application strings I assume you mean all text used in the application right?

**Comment by Zibri** [comment]
Yep.

**Comment by MikhaD** [comment]
@Zibri I have been thinking about this and wondering how to implement it without turning the code base into more of an illegible nightmare than it already is. I have not anything like this before and was wondering if you could aid my understanding.

Would I have to put all text in the app into external files and then reference indices in all the places I have text instead of the text itself? Is there any way to do this without making it difficult and tedious to figure out what is being said where when looking at the code?

**Comment by MikhaD** [comment]
Unless there is a simple solution for the problem mentioned above I am closing this issue. While I can see why this would be valuable, I do not intend to add multi language support to my game, and ultimately my goal is to make this game as good as possible, not provide a foundation for the community to build off.
I am flatted that people have been using it as such, but that is not my primary goal. I am not willing to make my code base harder to read in order to further that end.
